[package]
name = "fenrir"
version = "0.1.0"
edition = "2024"

[dependencies]
async-broadcast = "0.7.2"
async-channel = "2.5.0"
async-trait = "0.1.88"
futures-lite = "2.6.0"
tinyvec = "1.9.0"

[dev-dependencies]
tokio = { version = "1.47.0", features = ["rt", "macros"] }
