[package]
name = "fenrir"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
futures-lite = "2.6.0"

[dev-dependencies]
tokio = { version = "1.47.0", features = ["rt", "macros"] }
